cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

build:
  image: node:9.8.0
  stage: build
  script:
    - yarn install
    - npm run build

deploy_heroku_production:
  image: tmaier/dpl:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
